# fly.toml app configuration file generated for jdatingapp on 2023-08-09T22:55:19-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jdatingapp"
primary_region = "qro"

[build]
  image = "jmontiel1603/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dhny96hff"
  CloudinarySettings__ApiKey="727642375999624"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
